version: '3'
services:
  kubernetes_ubuntu:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "Kubernetes-Ubuntu"
    ports:
      - '9080:80'
      - '9081:3306'
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
